- hosts: all
  become: yes
  vars_files:
      - ./vars.yml
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Restart docker
      shell: systemctl restart docker

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day%

    - name: Install default packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Add users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell: "{{ item.shell }}"
        password: "{{ lookup('password', 'credentials/' + item.name + '/password.txt encrypt=md5_crypt') }}"
        state: present
      with_items: "{{ users.values() | list }}"
