- hosts: all
  become: yes
  vars_files:
      - ./vars.yml
  tasks:
    - name: Add users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell: "{{ item.shell }}"
        password: "{{ lookup('password', 'credentials/' + item.name + '/password.txt encrypt=md5_crypt') }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ item.ssh_key_filename + '_' + item.name }}
        state: present
      with_items: "{{ user_details }}"

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day%
      with_items: "{{ user_details }}"
