# TODO: create certs
# TODO: add registry deploy and configure
- hosts: master
  become: yes
  vars_files:
      - ./vars.yml
  tasks:
    - name: Install certbot
      community.general.snap:
        name: certbot
        classic: yes

    - name: create symlink
      shell: ln -s /snap/bin/certbot /usr/bin/certbot
